# Use a imagem oficial do Jenkins LTS
FROM jenkins/jenkins:lts

# Switch para o usuário root para instalar dependências
USER root

# Instalação de dependências necessárias
RUN apt-get update && \
    apt-get install -y sudo curl unzip git lcov mailutils postfix

# Define variável de ambiente para o diretório de instalação do Flutter
ENV FLUTTER_HOME /opt/flutter

#instala flutter
RUN mkdir -p $FLUTTER_HOME && \
    git clone https://github.com/flutter/flutter.git /opt/flutter

# Configura a variável de ambiente PATH para incluir o Flutter
ENV PATH=$PATH:/opt/flutter/bin

RUN git config --global --add safe.directory /opt/flutter

# Define permissões para o diretório do flutter
RUN chown -R jenkins:jenkins $FLUTTER_HOME

# Configurar o Postfix
COPY postfix/main.cf /etc/postfix/main.cf
COPY postfix/sasl_passwd /etc/postfix/sasl_passwd
RUN postmap /etc/postfix/sasl_passwd

# Reiniciar o serviço Postfix
RUN service postfix restart

# Volta para o usuário jenkins
USER jenkins
